packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
  - "@embedded-postgres/windows-x64"
  - "@embedded-postgres/darwin-arm64"
  - "@embedded-postgres/darwin-x64"
  - "@embedded-postgres/linux-x64"
  - "@embedded-postgres/linux-arm64"
  - "@node-rs/argon2"
